BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `User` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`username`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `RekamMedis` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`userID`	INTEGER NOT NULL,
	`Nama`	TEXT,
	`NIK`	TEXT,
	`Umur`	INTEGER,
	`JK`	INTEGER,
	`Alamat`	TEXT,
	`Tegangan`	REAL DEFAULT 0,
	`mAs`	REAL DEFAULT 0,
	`mGy`	REAL DEFAULT 0,
	`OutputRadiasi`	REAL DEFAULT 0,
	`Esak`	REAL DEFAULT 0,
	`DAP`	REAL DEFAULT 0,
	`imageName`	TEXT,
	FOREIGN KEY(`userID`) REFERENCES `User`(`ID`)
);
CREATE TABLE IF NOT EXISTS `AuthKey` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`owner`	INTEGER NOT NULL,
	`keys`	TEXT NOT NULL UNIQUE,
	`datecreated`	TEXT,
	`dateexpired`	TEXT,
	FOREIGN KEY(`owner`) REFERENCES `User`(`ID`)
);
CREATE INDEX IF NOT EXISTS `usernameIndex` ON `User` (
	`username`
);
CREATE INDEX IF NOT EXISTS `rekamMedisIDIndex` ON `RekamMedis` (
	`ID`,
	`userID`
);
CREATE INDEX IF NOT EXISTS `keyIndex` ON `AuthKey` (
	`keys`
);
COMMIT;
