BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `User` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`NIK`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL,
	`Role`	INTEGER NOT NULL DEFAULT 0,
	`Nama`	TEXT,
	`Umur`	INTEGER,
	`JK`	INTEGER,
	`Alamat`	TEXT
);
INSERT INTO `User` VALUES (1,'1000000000000000','$2y$10$nqV9t9D7.0vhieN4B1FD.uBO8O.H7.3S2.IRxhJAGAtDt6Xr8vj3W',1,'Administrator',0,0,'Rekam Medis');
CREATE TABLE IF NOT EXISTS `RekamMedis` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`userID`	INTEGER NOT NULL,
	`Nama`	TEXT,
	`Tegangan`	REAL DEFAULT 0,
	`mAs`	REAL DEFAULT 0,
	`mGy`	REAL DEFAULT 0,
	`OutputRadiasi`	REAL DEFAULT 0,
	`Esak`	REAL DEFAULT 0,
	`DAP`	REAL DEFAULT 0,
	`imageName`	TEXT,
	`datecreated`	TEXT,
	FOREIGN KEY(`userID`) REFERENCES `User`(`ID`)
);
CREATE TABLE IF NOT EXISTS `AuthKey` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`owner`	INTEGER NOT NULL,
	`keyss`	TEXT NOT NULL UNIQUE,
	`datecreated`	TEXT,
	`dateexpired`	TEXT,
	FOREIGN KEY(`owner`) REFERENCES `User`(`ID`)
);
CREATE INDEX IF NOT EXISTS `userIndex` ON `User` (
	`NIK`,
	`Role`
);
CREATE INDEX IF NOT EXISTS `rekamMedisIDIndex` ON `RekamMedis` (
	`ID`,
	`userID`
);
CREATE INDEX IF NOT EXISTS `keyIndex` ON `AuthKey` (
	`keyss`
);
COMMIT;
